name: dev-docs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_dev-docs:
    name: Build dev-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-tinytex@v2
      - run: |
          tlmgr update --self
          tlmgr install dvisvgm
          tlmgr install standalone
          tlmgr install pgf
          tlmgr install tikz-cd
          tlmgr install amsmath
      - run: bash scripts/dev-docs.sh
